### ISSUE TITLE
[BUG] Weird things happen when opening a proof and then creating a new puzzle

### ISSUE THREAD

**Issue by mattsweet417** [Bram-Hub/Legup#265]
### Description

When you open a proof of the same size and type as a puzzle you then create, the proof is essentially copied over to the new puzzle editor. Otherwise, if it is a different type or size, you are unable to edit the new puzzle.

### Steps to Reproduce

1. Open any proof in the proof editor
2. Press "File", then "Exit"
3. Click on "New Puzzle"
4. Create a new puzzle with valid dimensions

### Expected Behavior

The new puzzle should have nothing to do with the previous edited proof. I expect this is happening because of what views that the legup ui stores.

**Comment by charlestian23** [comment]
Was testing this issue with Nurikabe because I wasn't sure if it had been fixed. I do run into an issue, but it doesn't seem like the proof is "copied over" as the issue states. The board created was displayed to be empty, but I ran into the following error:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "edu.rpi.legup.model.tree.Tree.addNewTransition(edu.rpi.legup.model.tree.TreeNode)" because "tree" is null
	at edu.rpi.legup.history.EditDataCommand.executeCommand(EditDataCommand.java:63)
	at edu.rpi.legup.history.PuzzleCommand.execute(PuzzleCommand.java:26)
	at edu.rpi.legup.controller.ElementController.mouseReleased(ElementController.java:121)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at edu.rpi.legup.ui.ZoomablePane.processEvent(ZoomablePane.java:37)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
It does seem like LEGUP is trying to add another TreeTransition though, so seems like it thinks it is still in the proof editor when it is actually in the puzzle editor...

**Comment by charlestian23** [comment]
My guess is that there probably needs to be something that is "reset" every time you close out of the puzzle editor or the proof editor. Not sure how far you're into working on this issue though @19690ao

**Comment by charlestian23** [comment]
Well, seems like we know what to fix now :)
