### ISSUE TITLE
[BUG] TreeTentType class is not working properly and breaks Tree Tent proof editor

### ISSUE THREAD

**Issue by charlestian23** [Bram-Hub/LEGUP#508]
### Description

When attempting to create a Tree Tent proof, you are unable to make any changes to any of the cells on the board. When you attempt to do so, the following exception is thrown:
```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: class java.lang.Integer cannot be cast to class edu.rpi.legup.puzzle.treetent.TreeTentType (java.lang.Integer is in module java.base of loader 'bootstrap'; edu.rpi.legup.puzzle.treetent.TreeTentType is in unnamed module of loader 'app')
	at edu.rpi.legup.puzzle.treetent.TreeTentCell.getType(TreeTentCell.java:16)
	at edu.rpi.legup.puzzle.treetent.TreeTentElementView.drawElement(TreeTentElementView.java:20)
	at edu.rpi.legup.ui.boardview.ElementView.draw(ElementView.java:60)
	at edu.rpi.legup.ui.boardview.BoardView.drawBoard(BoardView.java:194)
	at edu.rpi.legup.puzzle.treetent.TreeTentView.drawBoard(TreeTentView.java:185)
	at edu.rpi.legup.ui.boardview.BoardView.draw(BoardView.java:189)
	at edu.rpi.legup.ui.ZoomablePane.paint(ZoomablePane.java:28)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5311)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedFPScales(RepaintManager.java:1721)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1630)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1570)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5259)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5069)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:879)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Steps to Reproduce

1. Open LEGUP
2. Click on "Solve Puzzle"
3. Open any Tree Tent puzzle
4. Click on the board and attempt to modify cells
5. Note the exception that is thrown

### Expected Behavior

Cells on the board should be able to be modified as per usual.

**Comment by Corppet** [comment]
I just tested Tree Tent and I am not running into any of these issues. What SDK versions is your environment and Gradle using?
